development:
  address: smtp.gmail.com
  port: 587
  authentication: :login
  domain: 'gmail.com'
  user_name: vikasdhakad989@gmail.com
  password: Va8817145293Va8817145293
  enable_starttls_auto: true

production:
  address: smtp.gmail.com
  port: 587
  authentication: :login
  domain: 'gmail.com'
  user_name: vikasdhakad989@gmail.com
  password: Va8817145293Va8817145293
  enable_starttls_auto: true
